server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcharith/Configuration-Repository
          default-label: main
#          clone-on-start: true
          username: mcharith


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

